version: '3.7'

services:
  webapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecgapp-server-img
    container_name: ecgapp-node-express
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
  mongo:
    image: mongo:latest
    container_name: ecg-app-db
    ports:
      - "27017:27017"
